config-version: 2
name: 'zendesk_source'
version: '0.16.0'
require-dbt-version: [">=1.3.0", "<2.0.0"]

models:
  zendesk_source:
    materialized: table
    +schema: zendesk_source
    tmp:
      materialized: view 
vars:
  zendesk_source:
    group: "{{ source('zendesk', 'group') }}"
    brand: "{{ source('zendesk', 'brand') }}"
    domain_name: "{{ source('zendesk', 'domain_name') }}"
    organization_tag: "{{ source('zendesk', 'organization_tag') }}"
    organization: "{{ source('zendesk', 'organization') }}"
    schedule: "{{ source('zendesk', 'schedule') }}"
    schedule_holiday: "{{ source('zendesk', 'schedule_holiday') }}"
    satisfaction_rating: "{{ source('zendesk', 'satisfaction_rating') }}"
    ticket: "{{ source('zendesk', 'ticket') }}"
    ticket_form_history: "{{ source('zendesk', 'ticket_form_history') }}"
    ticket_comment: "{{ source('zendesk', 'ticket_comment') }}"
    ticket_field_history: "{{ source('zendesk', 'ticket_field_history') }}"
    ticket_schedule: "{{ source('zendesk', 'ticket_schedule') }}"
    ticket_tag: "{{ source('zendesk', 'ticket_tag') }}"
    user_tag: "{{ source('zendesk', 'user_tag') }}"
    user: "{{ source('zendesk', 'user') }}"
    time_zone: "{{ source('zendesk', 'time_zone') }}"
    daylight_time: "{{ source('zendesk', 'daylight_time') }}"
    audit_log: "{{ source('zendesk', 'audit_log') }}"
    ticket_chat: "{{ source('zendesk', 'ticket_chat') }}"
    ticket_chat_event: "{{ source('zendesk', 'ticket_chat_event') }}"

  zendesk__ticket_passthrough_columns: []
  zendesk__user_passthrough_columns: []
  zendesk__organization_passthrough_columns: []
  zendesk_sources: []