config-version: 2

name: 'zendesk_source'
version: '0.1.0'

require-dbt-version: [">=0.18.0", "<0.20.0"]

models:
  zendesk_source:
    materialized: table
    tmp:
      materialized: view

vars:
  zendesk_source:
    group:                "{{ source('zendesk', 'group') }}"
    organization:         "{{ source('zendesk', 'organization') }}"
    schedule:             "{{ source('zendesk', 'schedule') }}"
    ticket:               "{{ source('zendesk', 'ticket') }}"
    ticket_comment:       "{{ source('zendesk', 'ticket_comment') }}"
    ticket_field_history: "{{ source('zendesk', 'ticket_field_history') }}"
    ticket_schedule:      "{{ source('zendesk', 'ticket_schedule') }}"
    ticket_tag:           "{{ source('zendesk', 'ticket_tag') }}"
    user:                 "{{ source('zendesk', 'user') }}"

    using_sla_policy: True
    using_schedules:  True
